spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cabinet
    username: postgres
    password: 2409
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8100

